# Kitty CheatSheet
# https://gist.github.com/AskinNet/0d0d4f7f0ee221f8362af9d9876d021a

# open new split (window) with cmd+d retaining the cwd
map alt+shift+w close_window
map alt+shift+n new_os_window
map alt+\ launch --location=hsplit --cwd=current
map alt+shift+d launch --location=vsplit --cwd=current

# open new tab with cmd+t
map alt+t new_tab

# switch between next and previous splits
map alt+]        next_window
map alt+[        previous_window

# clear the terminal screen
map alt+k combine : clear_terminal scrollback active : send_text normal,application \x0c

# jump to beginning and end of word
map alt+left send_text all \x1b\x62
map alt+right send_text all \x1b\x66

# jump to beginning and end of line
map alt+left send_text all \x01
map alt+right send_text all \x05

# Map cmd + <num> to corresponding tabs
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

# changing font sizes
map alt+equal    change_font_size all +2.0
map alt+minus    change_font_size all -2.0
map alt+0        change_font_size all 0

map alt+c        copy_to_clipboard
map alt+v        paste_from_clipboard
