# # kitty
# windowrule = tag +kitty, match:class (kitty)
# tag terminal defined in omarchy/default/hypr/apps/terminals.conf

# Float Steam
windowrule = float on, match:tag terminal, match:title ^(top)$
windowrule = float 1, match:tag terminal, match:title ^(btop)$
windowrule = float on, match:tag terminal, match:title ^(htop)$
# windowrulev2 = float,class:^(kitty)$,title:^(top)$
# windowrulev2 = float,class:^(kitty)$,title:^(btop)$
# windowrulev2 = float,class:^(kitty)$,title:^(htop)$
