windowrule = tag +wechat, match:class ^(wechat|Weixin)$


# windowrule = center on, match:tag wechat
windowrule = float on, match:tag wechat, match:title ^(朋友圈|Moments)$
# windowrule = no_focus on, match:tag wechat, match:title ^(朋友圈|Moments)$
# windowrule = no_dim on, match:tag wechat, match:title ^(朋友圈|Moments)$
# windowrule = stay_focused on, match:tag wechat, match:title ^(朋友圈|Moments)$
# windowrulev2 = float,class:^(wechat)$,title:^(朋友圈|Moments)$
# windowrulev2 = float,class:^(wechat)$,title:^(Video Call)$
