windowrule = tag +wechat, match:class ^(wechat|Weixin)$

# # 打破焦点锁定 (关键点在于拦截它的激活请求)
windowrule = stay_focused off, match:tag wechat

windowrule = tile on, match:tag wechat
# windowrule = float on, match:tag wechat, match:title ^(朋友圈|Moments)$
