# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="candy"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(osx colorize terminitor rvm sudo xcode command-not-found colored-man brew fasd autojump compleat rsync gradle sublime git git-flow svn tmux tmuxinator vagrant ruby capistrano gem rake rails php laravel4)

source $ZSH/oh-my-zsh.sh

# User configuration

# homebrew
export PATH="/usr/local/sbin:/usr/local/bin:$PATH"
# export MANPATH="/usr/local/man:$MANPATH"

# Android Platform Tools
#export JAVA_HOME=/usr/libexec/java_home
export ANDROID_HOME=/usr/local/opt/android-sdk
export ANDROID_NDK=/usr/local/Cellar/android-ndk/r9d

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi
export EDITOR=vim

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# Qyer Android
export QYER_KEYSTORE="/Users/icyleaf/Development/qyer/android/qyer.keystore"
export GRADLE_OPTS="-Xmx1024m -Xms256m -XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF8"

# QBot
export HUBOT_QQ_ID=2263155883
export HUBOT_QQ_PASS=qyer12345
export HUBOT_QQ_GROUP='穷游App开发'
export HUBOT_JENKINS_URL="http://mobile.dev:8888/"
export HUBOT_SLACK_TOKEN=xoxb-4073754715-GInn13RKiahjgigJbf9qdZCM
export HUBOT_INSTAGRAM_CLIENT_ID="394fb6f9a0a74c3f88cce00a7ab42ec2"

# Theos
export THEOS=/opt/theos

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

# Example aliases
alias zshconfig="vim ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"

alias xcplugins="ll ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/"

alias flushdns='dscacheutil -flushcache'
alias ns="sudo lsof -i -P"
#alias nc="lsof -Pni4 | grep LISTEN"
alias virtualenv='virtualenv --no-site-packages'
alias ox='open *.xcodeproj'
alias ow='open *.xcworkspace'
alias la='ll -a'

alias reload='source ~/.zshrc'
alias lsomzplugins='ls ~/.oh-my-zsh/plugins'
alias restartvbox='sudo /Library/StartupItems/VirtualBox/VirtualBox restart'
alias plist='plutil -p'

alias nginx.start='launchctl load ~/Library/LaunchAgents/homebrew.mxcl.nginx.plist'
alias nginx.stop='launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.nginx.plist'
alias nginx.restart='nginx.stop && nginx.start'
alias php-fpm.start="launchctl load -w ~/Library/LaunchAgents/homebrew-php.josegonzalez.php54.plist"
alias php-fpm.stop="launchctl unload -w ~/Library/LaunchAgents/homebrew-php.josegonzalez.php54.plist"
alias php-fpm.restart='php-fpm.stop && php-fpm.start'

function newrails() {
    rails new $1 -B -T -m https://raw.github.com/RailsApps/rails-composer/master/composer.rb
}
