
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here


# █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
# █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█

exec-once = keyd-application-mapper # start keyd for app remapping
exec-once = gauntlet --minimized  # cross-platform app launcher
# exec-once = wluma   # backlight auto adjust
exec-once = hyprsunset # blue light filter
exec-once = fcitx5 # IME
exec-once = synology-drive # Synology Drive

# slient exec-once: https://wiki.hyprland.org/FAQ/#how-do-i-autostart-my-favorite-apps
# exec-once = [workspace 1 silent] $browser
# exec-once = [workspace 2 silent] $term
# exec-once = [workspace 3 silent] $editor --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime
# exec-once = [workspace 9 silent] telegram-desktop


# █▀▀ █▄░█ █░█
# ██▄ █░▀█ ▀▄▀

# fix fcitx5
# env = QT_IM_MODULE,fcitx
env = XMODIFIERS,@im=fcitx
# env = GTK_IM_MODULE, wayland   # Crashes electron apps in xwayland
env = GTK_IM_MODULE, fcitx     # My Gtk apps no longer require this to work with fcitx5 hmm
env = SDL_IM_MODULE,fcitx
env = GLFW_IM_MODULE,ibus
env = INPUT_METHOD,fcitx

env = ANDROID_HOME,$HOME/Android/Sdksss
env = EDITOR,nvim # default editor


# █ █▄░█ █▀█ █░█ ▀█▀
# █ █░▀█ █▀▀ █▄█ ░█░

input {
    kb_layout = us
    follow_mouse = 1
    natural_scroll = true
    scroll_factor = 1.0

    touchpad {
        natural_scroll = true
    }

    sensitivity = 0
    force_no_accel = 1
    numlock_by_default = true
}


# // █▀ █▀█ █▀▀ █▀▀ █ ▄▀█ █░░
# // ▄█ █▀▀ ██▄ █▄▄ █ █▀█ █▄▄

# decoration {
#     dim_special = 0.3
#     active_opacity = 1
#     inactive_opacity = 0.9
#     fullscreen_opacity = 1
#     blur {
#         special = true
#     }
# }
