cask_args appdir: '/Applications'

def macos?
  RbConfig::CONFIG['host_os'].include?('darwin')
end

def minimal?
  is_minimal = ENV.fetch('BREW_MINIMUM', 'false')
  !(is_minimal == 'true' || is_minimal == 'yes' || is_minimal == '1')
end

# General tools
brew 'zsh'
brew 'git'
brew 'tig'
brew 'mosh'
brew 'btop'
brew 'helix'
brew 'gnupg'
brew 'zoxide'
brew 'eza'
# brew 'broot'
brew 'fzf'
brew 'watch'
brew 'wget'
brew 'ssh-copy-id'
brew 'bat'
brew 'fastfetch'
brew 'tree'
brew 'tmux'

unless minimal?
  # 第三方库
  tap 'kopia/kopia'

  # Development tools
  brew 'mise'
  brew 'httpie'
  brew 'mtr'

  brew 'axel'
  brew 'yt-dlp'
  brew 'kopia'

  # Blogging
  brew 'hugo'

  # Tmux
  brew 'reattach-to-user-namespace'

  # DevOps
  brew 'ansible'
  brew 'terraform'
  brew 'kubernetes-cli'
end

if macos?
  tap 'jandedobbeleer/oh-my-posh'

  # zsh themes
  brew 'oh-my-posh'

  # Development Tools
  brew 'terminal-notifier'
  brew 'postgresql@16'
  brew 'imagemagick'
  cask 'mitmproxy'

  # Tweaks
  brew 'pinentry-mac'
  brew 'mas'

  # macOS Apps
  cask 'raycast'
  cask 'google-chrome'
  cask 'iterm2'
  cask 'the-unarchiver'
  cask 'hiddenbar'
  # cask 'jordanbaird-ice' # requires sonama
  cask 'visual-studio-code'
  cask 'karabiner-elements'
  cask 'appcleaner'
  cask 'notion'
  cask 'iina'
  # cask 'android-studio'
  cask 'synology-drive'

  # macOS QuickLook Extensions
  cask 'provisionql'
  cask 'qlcolorcode'
  cask 'quicklook-json'

  # macOS non-ascii fonts for terminal
  cask 'font-meslo-lg-nerd-font'
end
