$scrPath = $HOME/.local/share/bin # set scripts path

# Main modifier
$mainMod = Super # super / meta / windows key

# Assign apps
$term = kitty
$editor = code
$file = dolphin
$browser = google-chrome-stable
$discord = vesktop --enable-wayland-ime
