
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄

# See https://wiki.hyprland.org/Configuring/Monitors/

monitor = eDP-1,preferred,auto,1.8
monitor = DP-2,preferred,auto-up,2
monitor = HDMI-A-1,preferred,auto-up,1.6
