# Default autostart: ~/.local/share/omarchy/default/hypr/autostart.conf

exec-once = uwsm app -- fcitx5 --replace -d
exec-once = uwsm app -- swaybg -i ~/.config/omarchy/current/background -m fill
exec-once = uwsm app -- swayosd-server
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# exec-once = omarchy-cmd-first-run
exec-once = uwsm app -- elephant
exec-once = uwsm app -- systembus-notify

# User specific autostart applications
exec-once = uwsm app -- hypridle                              # Idle management
exec-once = uwsm app -- walker --gapplication-service         # Launcher (elephant needed started first)
exec-once = uwsm app -- waybar                                # Status bar
exec-once = uwsm app -- wl-gammarelay-rs run                  # Per-monitor software brightness for external displays
exec-once = uwsm app -- hypr-input-switcher -w                # Input switch notification
exec-once = uwsm app -- synology-drive                        # Synology Drive
exec-once = uwsm app -- keyd-application-mapper               # start keyd for app remapping
# exec-once = uwsm app -- wluma   # backlight auto adjust
# exec-once = uwsm app -- hyprsunset # blue light filter

# instead of omarch default mako
exec-once = uwsm app -- swaync                                # Notification panel daemon
# exec-once = uwsm app -- nm-applet --indicator                 # Network manager applet
# exec-once = uwsm app -- blueman-applet                        # Bluetooth manager applet
exec-once = uwsm app -- udiskie --no-automount --smart-tray   # automount drives with tray icon

# Clipboard history (better then walker built-in clipboard module)
# needs install wl-paste, cliphist first
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Slow app launch fix -- set systemd vars
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all

# Run post-boot hooks after startup config has loaded
exec-once = sleep 2 && omarchy-hook post-boot
