# fix for the autoclosing filter modal (use stayfocused will force for all monitors)
# windowrule = tile,class:^(DBeaver)$
# source https://github.com/romanstingler/dotfiles/blob/80b5e7522d0c32802ff670d10c36c9b5228a3e1e/.config/hypr/hyprland.conf.bak#L215
windowrule = stay_focused on, match:class ^(wechat)$, match:float 1
