onboarding = false

[keys]
prefix = "ctrl+a"

[[keys.command]]
key = "prefix+ctrl+g"
type = "popup"
command = "lazygit"
description = "run lazygit"
width = "80%"
height = "80%"

[theme]
name = "nord"
auto_switch = false

[ui]
agent_panel_sort = "spaces"
confirm_close = true
prompt_new_tab_name = true
show_agent_labels_on_pane_borders = true
hide_tab_bar_when_single_tab = false

[ui.toast]
delivery = "herdr"
delay_seconds = 1

[ui.toast.herdr]
position = "bottom-right"

[ui.toast.clipboard]
enabled = true
position = "bottom-center"

[ui.sound]
enabled = true

[session]
resume_agents_on_restore = true

[remote]
manage_ssh_config = true

[experimental]
allow_nested = true
pane_history = true
