# Default autostart: ~/.local/share/omarchy/default/hypr/autostart.conf
# Extra autostart processes
# exec-once = uwsm app -- my-services

exec-once = uwsm app -- walker --gapplication-service # Launcher
exec-once = uwsm app -- hypr-input-switcher -w # Input switch notification
exec-once = uwsm app -- synology-drive # Synology Drive
exec-once = uwsm app -- keyd-application-mapper # start keyd for app remapping
exec-once = uwsm app -- gauntlet --minimized  # cross-platform app launcher
# exec-once = wluma   # backlight auto adjust
# exec-once = hyprsunset # blue light filter

# instead of omarch default mako
exec-once = uwsm app -- swaync # Notification daemon

# Clipboard history (better then walker built-in clipboard module)
# needs install wl-paste, cliphist first
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
