# Extra env variables
# Note: You must relaunch Hyprland after changing envs (use Super+Esc, then Relaunch)
# env = MY_GLOBAL_ENV,setting

# Desktop Environment
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland

# Scaling
env = GDK_SCALE,2
env = QT_SCALE_FACTOR,1.6
env = QT_AUTO_SCREEN_SCALE_FACTOR,1.6

# Fix fcitx5
# env = QT_IM_MODULE,fcitx
env = XMODIFIERS,@im=fcitx
# env = GTK_IM_MODULE, wayland   # Crashes electron apps in xwayland
# env = GTK_IM_MODULE, fcitx     # My Gtk apps no longer require this to work with fcitx5 hmm
env = SDL_IM_MODULE,fcitx
env = GLFW_IM_MODULE,ibus
env = INPUT_METHOD,fcitx

# Android SDK
env = ANDROID_HOME,$HOME/Android/Sdk
env = EDITOR,nvim # default editor

env = XDG_SESSION_TYPE,wayland
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = MOZ_ENABLE_WAYLAND,1

# Omarchy
env = OMARCHY_PATH,$HOME/.local/share/omarchy
