# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  kb_layout = us
  kb_options = compose:caps # ,grp:alts_toggle

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Increase sensitity for mouse/trackpack (default: 0)
  # sensitivity = 0.35

  follow_mouse = 1
  natural_scroll = true
  scroll_factor = 1.0

  touchpad {
    # Use natural (inverse) scrolling
    natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    # clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }

  sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
  force_no_accel = 1
  numlock_by_default = true
}

#See https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
  workspace_swipe_invert = true
  workspace_swipe_min_speed_to_force = 30
  workspace_swipe_cancel_ratio = 0.5
  workspace_swipe_create_new = true
  workspace_swipe_forever = false
}

# hyprland 0.51 add gesture support
# https://wiki.hypr.land/Configuring/Gestures/
# gesture = fingers, direction, action, options

gesture = 3, left, workspace
# gesture = 3, right, workspace
gesture = 3, down, mod: ALT, close
gesture = 3, up, scale: 1, float
# gesture = 3, left, scale: 1.5, float
