general {
  gaps_in = 4
  gaps_out = 4
  border_size = 2
  col.active_border = rgba(ca9ee6ff) rgba(f2d5cfff) 45deg
  col.inactive_border = rgba(b4befecc) rgba(6c7086cc) 45deg
  layout = dwindle
  resize_on_border = true
}

decoration {
  rounding = 5
  shadow:enabled = false

  blur {
    enabled = yes
    size = 6
    passes = 3
    new_optimizations = on
    ignore_opacity = on
    xray = false
  }
}

animations {
  enabled = true
  bezier = wind, 0.05, 0.9, 0.1, 1.05
  bezier = winIn, 0.1, 1.1, 0.1, 1.1
  bezier = winOut, 0.3, -0.3, 0, 1
  bezier = liner, 1, 1, 1, 1
  animation = windows, 1, 6, wind, slide
  animation = windowsIn, 1, 6, winIn, slide
  animation = windowsOut, 1, 5, winOut, slide
  animation = windowsMove, 1, 5, wind, slide
  animation = border, 1, 1, liner
  animation = borderangle, 1, 30, liner, once
  animation = fade, 1, 10, default
  animation = workspaces, 1, 5, wind
}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  enable_anr_dialog = false
  force_default_wallpaper = 0
  focus_on_activate = false
  vrr = 2
}

binds {
  allow_workspace_cycles = true
}

# If you're using fractional scaling or any scaling in Hyprland,
# the emulator will launch in a blurred window. To fix that add the following code to your hyprland.conf
xwayland {
  enabled = true
  force_zero_scaling = true
}
