# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale
# You must relaunch Hyprland after changing any envs (use Super+Esc, then Relaunch)

#              ┌───────────────────┐
#              │                   │
#              │  HS 140KP (ID 1)  │
#              │                   │
#  ┌───────────└───────────────────┘──────┐
#  │                      │               │
#  │                      │  eDP-1 (ID 0) │
#  │     LG 4K (ID 2)     │               │
#  │                      │───────────────┘
#  │                      │
#  └──────────────────────┘

# internal display (ID 0) / eDP-1
monitor = desc:Tianma Microelectronics Ltd. TL140ADXP24-0, 2880x1800@120, 0x0, 1.6

# external displays

## HS 140KP (ID 1) / HDMI-A-1
monitor = desc:YTH HS-140KP, 3840x2160@60, -960x-1080, 2

## LG 4K (ID 2) / DP-2
monitor = desc:LG Electronics LG HDR 4K 0x0000323A, 3840x2160@60, -2560x0, 1.5

# Parents home
# monitor = desc:AOC 2360 AEUG319A001072, 1920x1080@60, 1800x0, 1
# monitor = desc:Dell Inc. DELL 2209WA H737H9561TKL, 1680x1050@60, 1800x0, 1

# Xiaoxin Pad
# monitor = desc:AOC 2360 AEUG39A001072, 1920x1080@60, 1800x0, 1

# Tokyo
#                     ┌──────────────────┐
# ┌───────────────────│                  │
# │                   │                  │
# │                   │                  │
# │     HS 140KP      │     16:10 DIY    │
# │                   │                  │
# │                   │                  │
# └───────────────────└──────────────────┘
#            │                │
#            │                │
#            │     eDP-1      │
#            │                │
#            │                │
#            └────────────────┘
## 16:10 monitor for work
monitor = desc:Invalid Vendor Codename - RTK UHD, 3240x2160@60, 1000x-1080, 2

# Special monitor workspace
workspace = 1, name:Main, monitor:eDP-1, default:true
workspace = 11, name:Media, monitor:HDMI-A-1, default:true
workspace = 21, name:Browser, monitor:DP-2, default:true
