# requires google-chrome/chromium from AUR
# wayland
--enable-wayland-ime
--enable-features=UseOzonePlatform,TouchpadOverscrollHistoryNavigation,WaylandWindowDecorations
--ozone-platform-hint=auto

# enable wayland can enable scale but only one window can trigger fcitx5 input
--ozone-platform=wayland

# --ozone-platform=x11
# --force-device-scale-factor=1.4

# 开启可以实现长按 backspace 地址栏连续删除但多 chrome 窗口只有一个能激活 fcitx5 输入
# 可能有关的 ref https://github.com/swaywm/sway/issues/8276  https://github.com/electron/electron/issues/33662
--wayland-text-input-version=3

--disable-waylandc-per-window-scalinng

# Force GPU acceleration
--enable-zero-copy
--ignore-gpu-blocklist
--disable-gpu-driver-bug-workarounds

# Disable len overlay icon
--disable-features=LensOverlay

# Disable ask search suggestions
--disable-features=OmniboxContextualSuggestions

# Chromium crash workaround for Wayland color management on Hyprland - see https://github.com/hyprwm/Hyprland/issues/11957
--disable-features=WaylandWpColorManagerV1

# omarchy extensions
--enable-features=TouchpadOverscrollHistoryNavigation
--load-extension=~/.local/share/omarchy/default/chromium/extensions/copy-url
